// Customer-facing agent roster. Names match the investor deck and the family deck, not
// the internal codenames. Copy comes from the website copy pack (v2). No em dashes.

export type AgentStatus = "live" | "pilot" | "coming";
export type AgentGroup = "sales" | "intelligence" | "content" | "quoting" | "inbox" | "backoffice";

export type Agent = {
  slug: string;
  name: string;
  tagline: string;
  group: AgentGroup;
  icon: string; // lucide icon name, resolved in components/AgentIcon.tsx
  cadence: { big: string; label: string }; // the stat on the card
  does: string;
  outputs: string;
  how: string;
  when: string;
  custom: string;
  status: AgentStatus;
};

export const agentGroups: { key: AgentGroup; title: string; lead?: string }[] = [
  { key: "sales", title: "Sales enablement agents" },
  { key: "intelligence", title: "Market intelligence agents" },
  { key: "content", title: "Content agents" },
  { key: "quoting", title: "Quoting and documents" },
  { key: "inbox", title: "Executive inbox" },
  { key: "backoffice", title: "Back office", lead: "Coming soon. Early access goes to clients who raise their hand first." },
];

export const agents: Agent[] = [
  {
    slug: "lead-engine",
    name: "Lead Engine",
    tagline: "A research team that never sleeps and never pads a list.",
    group: "sales",
    icon: "Radar",
    cadence: { big: "2x", label: "runs a week" },
    does: "Finds companies worth insuring in the markets you choose, checks that each one is real, identifies the decision makers, and scores every lead out of 100.",
    outputs: "Scored, verified lead cards landing directly in your pipeline. Anything it cannot verify gets dropped, not padded in to look like more.",
    how: "It scans for matches against your criteria, verifies and scores each one, and files it straight into your pipeline the moment it is done.",
    when: "Every Monday and Thursday morning, automatically.",
    custom: "Your target industries, company size and geography are all set to your business, and you can pause the search or change the target market any time from your dashboard.",
    status: "live",
  },
  {
    slug: "lead-processor",
    name: "Lead Processor",
    tagline: "The instant follow-through behind every lead, before you would even think to ask.",
    group: "sales",
    icon: "Zap",
    cadence: { big: "0s", label: "delay after each find" },
    does: "The moment Lead Engine finds a new prospect, this is what enriches it, builds the full lead card, and gets the alert to the right person.",
    outputs: "A fully enriched lead card and an instant alert, with no delay between discovery and notification.",
    how: "It fires automatically the second Lead Engine finishes a run. No schedule of its own, no manual step, ever.",
    when: "Immediately after every Lead Engine run.",
    custom: "Nothing to configure. It is silent infrastructure. You just choose where the alert lands: WhatsApp, email, or your dashboard.",
    status: "live",
  },
  {
    slug: "pre-call-intelligence",
    name: "Pre-Call Intelligence",
    tagline: "So you never walk into a meeting cold.",
    group: "sales",
    icon: "FileSearch",
    cadence: { big: "1", label: "brief per call" },
    does: "Researches a company and its market before a meeting, so you walk in knowing what changed this month and what is worth asking about.",
    outputs: "A real research brief with the takeaways that matter, ready before the call.",
    how: "It pulls together what is genuinely useful to know about the lead and their market and writes it as a clear briefing, not a pile of links.",
    when: "Every Monday morning for the week's meetings, and on demand, one tap, before any call.",
    custom: "What it prioritises (financial signals, recent news, decision-maker background) can be tuned to what matters most in your sales process.",
    status: "live",
  },
  {
    slug: "speed-to-lead-drafting",
    name: "Speed-to-Lead Drafting",
    tagline: "A personal first email, ready before the lead goes cold.",
    group: "sales",
    icon: "PenLine",
    cadence: { big: "150", label: "words, max, per email" },
    does: "Writes a short, personal first-touch email for every top-scoring new lead, in your own language.",
    outputs: "A ready-to-send email draft per lead, under 150 words, sitting in your approval queue.",
    how: "It drafts automatically for leads needing a first touch, and every draft waits for a person to approve it. It never sends on its own.",
    when: "Every Tuesday and Thursday morning, automatically.",
    custom: "Tone, language (English or French) and messaging angle are all set to match how your team actually talks to prospects.",
    status: "live",
  },
  {
    slug: "lead-activation",
    name: "Lead Activation",
    tagline: "The high-touch version, for the leads worth extra attention.",
    group: "sales",
    icon: "Sparkles",
    cadence: { big: "3", label: "openers per lead" },
    does: "Digs deeper into one specific lead you flag as worth extra effort and writes three different email approaches to choose from.",
    outputs: "Three distinct, ready-to-send email drafts for a single high-value lead, each taking a different angle.",
    how: "One WhatsApp command, and it digs into the lead, their owner and their business, then drafts three genuinely different openings in minutes.",
    when: "On demand, whenever a lead deserves the extra investment.",
    custom: "Built for your best opportunities specifically. Use it as often or as rarely as your pipeline calls for it.",
    status: "live",
  },
  {
    slug: "follow-up-monitor",
    name: "Follow-Up Monitor",
    tagline: "Never lets a warm lead go cold from being forgotten.",
    group: "sales",
    icon: "BellRing",
    cadence: { big: "7/14", label: "day reminder and draft" },
    does: "Watches every outreach email that has gone out and makes sure silence never becomes a dead lead.",
    outputs: "A WhatsApp reminder after 7 days of no reply, and a fully drafted follow-up email after 14 days, ready for your approval.",
    how: "It checks every active lead's reply status continuously, and acts the moment one has gone quiet too long.",
    when: "Checks every morning, automatically, in the background.",
    custom: "You can review, edit or mute the reminders any time from your dashboard, and the follow-up timing can be adjusted to how aggressively you want to pursue a quiet lead.",
    status: "live",
  },
  {
    slug: "instant-proposals",
    name: "Instant Proposals",
    tagline: "A client-ready proposal in under two minutes.",
    group: "sales",
    icon: "FileText",
    cadence: { big: "<2", label: "minutes per proposal" },
    does: "Turns a lead into a complete, client-ready insurance proposal, the kind of document that used to take a full day.",
    outputs: "A full, ready-to-send proposal draft, generated on demand.",
    how: "One command from your phone, and it pulls together everything a proposal needs into a finished draft.",
    when: "On demand, whenever you need a proposal out the door. Nothing waits on a schedule.",
    custom: "Structure and content adapt to the specific lead and opportunity. No generic, one-size-fits-all template.",
    status: "live",
  },
  {
    slug: "pitch-decks",
    name: "Pitch Decks",
    tagline: "A branded deck, grounded in real numbers, never an invented one.",
    group: "sales",
    icon: "Presentation",
    cadence: { big: "PDF", label: "branded deck per lead" },
    does: "Builds a branded pitch deck for one specific company, written around its sector and country.",
    outputs: "A finished, branded PDF deck, ready to review and send.",
    how: "It pulls in real, current market context relevant to that lead's industry and geography and writes the deck around it. It only uses figures it can actually find.",
    when: "On demand, or automatically the moment outreach to that lead is approved.",
    custom: "Branding, structure and market focus are all set to your business and your target client, and you always review the PDF before it reaches a prospect.",
    status: "live",
  },
  {
    slug: "morning-brief",
    name: "Morning Brief",
    tagline: "One brief, every morning, instead of five places to check.",
    group: "intelligence",
    icon: "Sunrise",
    cadence: { big: "1", label: "brief every morning" },
    does: "Pulls together everything every other agent found overnight (pipeline, new leads, market signals, pending approvals, today's call list) into one short brief.",
    outputs: "One readable daily brief that replaces checking multiple systems separately.",
    how: "It assembles what is flowing in from everywhere else into a single, prioritised summary, ready before your day starts.",
    when: "Every morning, automatically, before the day starts. Also available on demand any time from your dashboard.",
    custom: "What sections it includes and how it is prioritised can be adjusted to how your team actually starts its day.",
    status: "live",
  },
  {
    slug: "opportunity-scanner",
    name: "Opportunity Scanner",
    tagline: "Spots the moment a company suddenly needs cover.",
    group: "intelligence",
    icon: "Crosshair",
    cadence: { big: "Daily", label: "scan of your markets" },
    does: "Scans the news every morning for new contracts, tenders, expansions and investments in your markets: the moments that create real demand.",
    outputs: "Flagged opportunity signals feeding straight into your Morning Brief.",
    how: "It watches your target markets continuously and surfaces the signals genuinely worth acting on.",
    when: "Every morning, automatically.",
    custom: "The markets and sectors it watches are entirely set to your footprint and targets.",
    status: "live",
  },
  {
    slug: "network-intelligence",
    name: "Network Intelligence",
    tagline: "Points out the introductions actually worth making.",
    group: "intelligence",
    icon: "Network",
    cadence: { big: "Daily", label: "relationship signals" },
    does: "Follows business-community events, chamber-of-commerce activity and relationship signals across your markets.",
    outputs: "Relevant network and relationship signals, filtered so irrelevant mentions never get flagged as opportunities.",
    how: "It tracks connection and community activity relevant to your markets and surfaces only what is genuinely useful.",
    when: "Every morning, automatically.",
    custom: "Which regions and industries it tracks can be adjusted any time.",
    status: "live",
  },
  {
    slug: "country-risk",
    name: "Country Risk",
    tagline: "Political, security and currency shifts, translated into what they mean for insurance.",
    group: "intelligence",
    icon: "Globe",
    cadence: { big: "Weekly", label: "brief per market" },
    does: "Delivers a plain-language weekly read on the political, security and currency developments that actually affect an insurance book.",
    outputs: "A weekly country-risk brief per active market.",
    how: "It tracks risk-relevant developments across your specified markets and explains what has changed and why it matters.",
    when: "Every Wednesday morning.",
    custom: "The markets it watches are entirely set to your footprint and expansion plans.",
    status: "live",
  },
  {
    slug: "competitor-tracking",
    name: "Competitor Tracking",
    tagline: "What competing brokers and insurers are actually doing, before a client mentions it first.",
    group: "intelligence",
    icon: "Eye",
    cadence: { big: "Weekly", label: "competitor report" },
    does: "Tracks what rival brokers, agents and insurers in your space are actually doing: new products, pricing moves, hires, partnerships.",
    outputs: "A weekly competitor intelligence report.",
    how: "It monitors competitor activity relevant to your market and surfaces what is genuinely worth knowing.",
    when: "Every Monday morning.",
    custom: "Which competitors and markets it tracks are set to your specific competitive landscape.",
    status: "live",
  },
  {
    slug: "regulatory-watch",
    name: "Regulatory Watch",
    tagline: "Regulatory changes, caught before they catch you.",
    group: "intelligence",
    icon: "Scale",
    cadence: { big: "Weekly", label: "compliance brief" },
    does: "Checks every week for regulatory and compliance changes across your target markets, and explains in plain language what they mean for your business.",
    outputs: "A weekly regulatory and compliance brief.",
    how: "It tracks regulatory activity across your specified markets continuously and flags what actually affects how you are allowed to operate.",
    when: "Every Monday morning.",
    custom: "The markets and licensing areas it watches are set to where you actually operate.",
    status: "live",
  },
  {
    slug: "weekly-strategy-memo",
    name: "Weekly Strategy Memo",
    tagline: "A blunt, numbers-first memo. Not generic advice.",
    group: "intelligence",
    icon: "Compass",
    cadence: { big: "3", label: "moves for the week" },
    does: "Reviews your whole pipeline (leads, market signals, pending approvals) and writes three concrete moves for the week ahead.",
    outputs: "A weekly strategy memo with specific, actionable next steps, not generic commentary.",
    how: "It reviews everything flowing through your account against proven growth and sales frameworks and distils it into three moves.",
    when: "Every Friday morning.",
    custom: "You read it and decide. Nothing acts on it without you, and its focus areas can be tuned to your priorities.",
    status: "live",
  },
  {
    slug: "content-engine",
    name: "Content Engine",
    tagline: "Content grounded in something real, not generic filler.",
    group: "content",
    icon: "Megaphone",
    cadence: { big: "2x", label: "drafts a week" },
    does: "Turns real market news into ready-to-post content in your own voice: LinkedIn, Instagram, Facebook, TikTok.",
    outputs: "Ready-to-review social post drafts, seeded by real signals your Market Intelligence agents just found.",
    how: "It pulls from real, current signals relevant to your market and writes content grounded in them, rather than generating generic filler.",
    when: "Every Tuesday and Thursday morning.",
    custom: "Tone, platform, language (English or French) and content pillars are all set to your brand voice and audience. Nothing publishes without your sign-off.",
    status: "live",
  },
  {
    slug: "content-calendar",
    name: "Content Calendar",
    tagline: "So posting never starts from a blank page on a Monday.",
    group: "content",
    icon: "CalendarDays",
    cadence: { big: "Sun", label: "plan for the week ahead" },
    does: "Plans your whole week of content in advance: a theme for each day, angles drawn from live market signals, and one bigger anchor piece.",
    outputs: "A full, structured weekly content plan, ready before the week begins.",
    how: "It organises what has been drafted and what is coming into a clear, plannable schedule.",
    when: "Every Sunday evening.",
    custom: "You can reshuffle the plan any time from your dashboard, and cadence and platform mix are set to how and where you want to show up.",
    status: "live",
  },
  {
    slug: "health-quoter",
    name: "Health Quoter",
    tagline: "A priced health quote in seconds, never a guess.",
    group: "quoting",
    icon: "HeartPulse",
    cadence: { big: "Secs", label: "per health quote" },
    does: "Prices individual and family health cover across insurers in seconds, straight from the real tariffs.",
    outputs: "An instant, branded, accurate health insurance quote.",
    how: "It lives in your browser and reads live from your own connected rate books. No hardcoded prices, ever.",
    when: "On demand, whenever someone needs a number. No schedule, because it is self-serve.",
    custom: "Your team opens it and quotes instantly, any time, without waiting on us. Branding and rate books are yours.",
    status: "live",
  },
  {
    slug: "motor-quoter",
    name: "Motor Quoter",
    tagline: "The vehicle's real value, filled in automatically, so the first quote is the right one.",
    group: "quoting",
    icon: "Car",
    cadence: { big: "Secs", label: "per motor quote" },
    does: "Prices motor cover instantly, with the vehicle's market value calculated automatically as part of the quote.",
    outputs: "An instant, branded, accurate motor insurance quote.",
    how: "It lives in your browser, connected to your own rate books, and pulls a fair vehicle valuation in automatically.",
    when: "On demand, whenever a quote is needed.",
    custom: "Fully self-serve for your team. Quote directly with clients, any time.",
    status: "live",
  },
  {
    slug: "vehicle-value-finder",
    name: "Vehicle Value Finder",
    tagline: "So the sum insured is never argued about at claim time.",
    group: "quoting",
    icon: "Gauge",
    cadence: { big: "Auto", label: "on every motor quote" },
    does: "Finds a fair market value for a vehicle before the quote is finalised.",
    outputs: "An accurate, defensible market value, built into every motor quote automatically.",
    how: "It runs invisibly inside the Motor Quoter. No separate step, no extra click.",
    when: "Automatically, every time a motor quote is run.",
    custom: "Nothing to configure. It simply works, every time.",
    status: "live",
  },
  {
    slug: "document-studio",
    name: "Document Studio",
    tagline: "A finished, branded document, ready to send, not ready to be reformatted.",
    group: "quoting",
    icon: "FileOutput",
    cadence: { big: "1", label: "click from quote to document" },
    does: "Turns any quote into a clean, branded offer card, comparison sheet or proposal document.",
    outputs: "A polished, ready-to-send document generated straight from a live quote.",
    how: "It lives in your browser and builds the document the moment a quote is ready.",
    when: "On demand, right after any quote is built.",
    custom: "Branding and document type are yours to set. Your team generates it themselves, the moment they need it.",
    status: "live",
  },
  {
    slug: "executive-inbox-intelligence",
    name: "Executive Inbox Intelligence",
    tagline: "Reads your inbox every morning. Writes like you. Never sends without you.",
    group: "inbox",
    icon: "Inbox",
    cadence: { big: "Daily", label: "sorted inbox and drafts" },
    does: "Reads a decision-maker's inbox every morning, sorts what actually matters, and drafts replies in their own voice.",
    outputs: "A sorted, triaged inbox and ready-to-review reply drafts, every morning.",
    how: "It learns how you specifically write and what matters most to you over time, getting sharper every week, and it never sends anything on its own.",
    when: "Every morning, automatically.",
    custom: "Entirely personal. It is built around one person's inbox, their contacts and their voice, not a generic company-wide setting.",
    status: "pilot",
  },
  {
    slug: "cipher",
    name: "CIPHER",
    tagline: "The Accounting Engine: insurer statements reconciled to the cent, ready for your sign-off.",
    group: "backoffice",
    icon: "Calculator",
    cadence: { big: "Monthly", label: "close, prepared for you" },
    does: "Reconciles financial statements and insurer bordereaux automatically, and helps your accounting team build and maintain the Excel sheets and balance-sheet reconciliations they currently do by hand.",
    outputs: "A matched, reconciled statement with every unexplained item flagged clearly, not buried in a spreadsheet, plus the working Excel files your team already relies on, built and maintained for you.",
    how: "The underlying matching logic has already been validated to the cent against real financial statements across multiple months. It already runs on our own brokerage's books every month, and running the same month twice gives exactly the same result.",
    when: "On your schedule, matching how often you currently reconcile.",
    custom: "Fully. Built around your accounting team's exact structure, sheet formats and preferences, not a generic template forced onto your process.",
    status: "pilot",
  },
  {
    slug: "claims-and-renewals",
    name: "Claims & Renewals",
    tagline: "Nothing slips through the cracks. Coming soon.",
    group: "backoffice",
    icon: "RefreshCw",
    cadence: { big: "Soon", label: "in development" },
    does: "Tracks policies approaching renewal, monitors claims communication so a client is never left wondering where things stand, and follows up on outstanding receivables.",
    outputs: "Renewal alerts before a policy lapses, claims-status visibility, and receivables follow-up reminders.",
    how: "It is designed on the same pattern as every other agent in the fleet: watch a condition, act when it is true.",
    when: "To be confirmed as it moves from design into build.",
    custom: "Will be built around your specific renewal cycle and claims process, the same way every other agent here is.",
    status: "coming",
  },
];

export const agentBySlug = (slug: string) => agents.find((a) => a.slug === slug);
export const liveAgents = agents.filter((a) => a.status === "live");
